[package]
name = "bsp-f446"
version = "0.1.0"
edition = "2021"

[dependencies]
defmt.workspace = true
embassy-stm32 = { workspace = true, features = ["defmt"] }
embassy-usb.workspace = true
embassy-executor.workspace = true
embassy-time.workspace = true
static_cell = "2.0"
gs-usb-protocol = { path = "../gs-usb-protocol" }