[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32F446RE"
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "trace"

[alias]
# Comandos para testear el workspace nativamente en tu PC.
# - Para probar todo: `cargo test-linux`
# - Para probar un crate específico: `cargo test-linux -p gs-usb-protocol`
test-linux = "test --target x86_64-unknown-linux-gnu"
test-win = "test --target x86_64-pc-windows-msvc"
test-mac = "test --target aarch64-apple-darwin"